### PR TITLE
fix: replace all dot chars during normalization

### LINKED ISSUE #579: [BUG] Only first dot (.) of normalized output key is replaced
## Vault server version
v1.19.2

## vault-action version
v3.3.0

## Describe the bug
If multiple dots (`.`) are contained in the name of a secret, only the first dot is replaced (`__`). All other dots are removed.

## To Reproduce
Create a secret named i.e. `my.secret.value`
Expected output key: `MY__SECRET__VALUE`
Actual output key: `MY__SECRETVALUE`

## Expected behavior
According to the [documentation](https://github.com/hashicorp/vault-action/blob/4d5899dd0e485089ac886c14527af8169532a201/README.md?plain=1#L736) and a response to another [issue](https://github.com/hashicorp/vault-action/issues/577#issuecomment-2797367254), this is not intended, and all dots should be replaced with `__` instead of just the first one.

## Additional context
Problem should be this line: [.replace(".", "__")](https://github.com/hashicorp/vault-action/blob/4d5899dd0e485089ac886c14527af8169532a201/src/utils.js#L8)

> If pattern is a string, only the first occurrence will be replaced.

(see [replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) )

### PR DESCRIPTION
**Pull request by fairclothjm**
### Description

Closes #579 

### Checklist
- [x] Added [CHANGELOG](https://github.com/hashicorp/vault-action/blob/master/CHANGELOG.md) entry (only for user-facing changes)

### Community Note

* Please vote on this pull request by adding a 👍
  [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original pull request comment to help the community and maintainers
  prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request
  followers and do not help prioritize the request

### CODE REVIEW

File: dist/index.js [hunk 1]
```diff
@@ -19309,7 +19309,7 @@ module.exports = {
  */
 function normalizeOutputKey(dataKey, upperCase = false) {
   let outputKey = dataKey
-    .replace(".", "__")
```
Comment (tvoran) [inline dist/index.js:19312]: IIRC we used to wait to update `dist/index.js` until release time?

**Review by tvoran — APPROVED** [review]

File: dist/index.js (hunk 1 above)
Comment (fairclothjm) [reply dist/index.js:19312]: Yes you are correct. I can't remember why I started including this in PRs. But at one point I think I had a good reason... Maybe it was so the main ref was up-to-date in case people wanted to pull that in?

Comment (fairclothjm) [reply dist/index.js:19312]: Evidence of that here: https://github.com/hashicorp/vault-action/pull/522#issuecomment-2310331130

Comment (tvoran) [reply dist/index.js:19312]: Yeah I think the concern was that `main` could be unstable in between releases and could break people that were pointing to `@main`. But that was early days here, maybe we're not as worried about that now.
